Custom service added

diff --git a/Service_check b/Service_check
--- a/Service_check
+++ b/Service_check
@@ -150,19 +150,69 @@ done
 EOT
 }
 
-read -p "Service Type like mariadb or radius " i
+
+function custom() {
+
+read -p "Enter Service Name separated by space: " str  #reading string value  
+  
+# IFS='' #setting space as delimiter  
+# read -ra SER <<<"$str" #reading str as an array as tokens separated by IFS 
+echo 'Service adding for Radius'
+cat >/opt/service_check.sh <<"EOT"
+#!/usr/bin/env bash
+# -----------------------------------------------------------
+# Script for check services status and manage services
+# Govind Kumar <govind.kumar@infinitylabs.in>
+# -----------------------------------------------------------
+
+# declare serice array
+declare SER=( SERR )
+n=${#SER[*]}
+LOG="/var/log/service_check.log"
+
+while true;
+do
+    printf "\n-------------------$(date +"%d-%m-%Y %H:%M:%S")----------------------\n" >> ${LOG}
+
+    for ((i=0; i<n; i++));
+    do
+        check=$(systemctl is-failed "${SER[$i]}")
+
+        if [[ "${check}" != "active" ]]; then
+
+            echo 1 ${CHECK}
+#            systemctl stop ${SER[i]}
+            systemctl reset-failed ${SER[i]}
+            systemctl start ${SER[i]}
+
+            if [ $? -eq 0 ]; then
+                echo "${SER[$i]} service successfully started on $(date +"%d-%m-%Y %H:%M:%S")" >> "$LOG"
+            elif [ $? -ne 0 ]; then
+                echo "${SER[$i]} service failed to start on $(date +"%d-%m-%Y %H:%M:%S")" >> "$LOG"
+            fi
+        else
+            printf "Service ${SER[$i]}\t[OK]\n" >> "$LOG"
+        fi
+    done
+    sleep 10
+done
+EOT
+sed -i "s/SERR/$str/g" service_check.sh
+}
+
+read -p "Service Type like mariadb or radius or custom " i
 case $i in 
     mariadb|mysql)
-
     mariadb
     ;;
     radius|haproxy|keepalived)
-
     radius
     ;;
     MK|mk)
-    
     MK
+    ;;
+    custom)
+    custom
     ;;
     *)
     echo "unknown"
@@ -172,3 +222,4 @@ esac
 chmod +x /opt/service_check.sh
 systemctl enable --now service_check.service
 systemctl is-active service_check.service
+
